'use client';
import {useState} from 'react';
import {Search,ChevronDown,ChevronUp,ShieldCheck} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_BASE||'http://localhost:8000';
export default function SearchPage(){
 const [origin,setOrigin]=useState('DEL'),[destination,setDestination]=useState('BOM'),[date,setDate]=useState('2026-09-20'),[data,setData]=useState<any>(null),[open,setOpen]=useState('');
 const submit=(e:any)=>{e.preventDefault();fetch(`${API}/api/v1/search?origin=${origin}&destination=${destination}&departure_date=${date}`).then(r=>r.json()).then(setData)};
 return <main className="max-w-6xl mx-auto p-4 sm:p-8 space-y-6"><form onSubmit={submit} className="bg-white border rounded-2xl p-5 grid sm:grid-cols-4 gap-3"><input value={origin} onChange={e=>setOrigin(e.target.value.toUpperCase())} className="border rounded-xl px-3"/><input value={destination} onChange={e=>setDestination(e.target.value.toUpperCase())} className="border rounded-xl px-3"/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border rounded-xl px-3"/><button className="bg-blue-600 text-white rounded-xl font-bold flex gap-2 items-center justify-center"><Search size={16}/>Compare fares</button></form>{data&&<><div className={`rounded-2xl border p-4 ${data.data_mode==='LIVE'?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}>Data mode: <b>{data.data_mode}</b>. Live public collection has source-level provenance; demo results are labelled and are not official statistics.</div><div className="space-y-4">{data.flights.map((f:any)=><div key={f.flight_id} className="bg-white border rounded-2xl p-5"><div className="grid md:grid-cols-4 gap-4 items-center"><div><div className="font-black">{f.airline_name}</div><div className="text-xs text-slate-500">{f.flight_number}</div></div><div>{f.origin} → {f.destination}<div className="text-xs text-slate-500">{f.departure_time} · {f.duration}</div></div><div><div className="text-xs text-slate-500">Starting fare</div><div className="text-2xl font-black">₹{f.cheapest_fare.toLocaleString()}</div></div><button onClick={()=>setOpen(open===f.flight_id?'':f.flight_id)} className="border rounded-xl px-4 py-2 font-bold flex items-center justify-center gap-2">Compare {open===f.flight_id?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button></div>{open===f.flight_id&&<div className="mt-4 space-y-2">{f.offers.map((o:any)=><div key={o.provider_id} className="border rounded-xl p-4 flex justify-between"><div><div className="font-bold">{o.provider_name}</div><div className="text-xs text-slate-500 flex gap-1 items-center"><ShieldCheck size={12}/> {o.source_status}</div></div><div className="text-right"><div className="font-black">₹{o.total_fare.toLocaleString()}</div><div className="text-xs text-slate-500">Base ₹{o.breakdown.base_fare.toLocaleString()} · Taxes ₹{o.breakdown.taxes.toLocaleString()} · Fees ₹{o.fees.toLocaleString()}</div></div></div>)}</div>}</div>)}</div></>}</main>
}
